"""Acceptance tests for place_reconstruct (the puzzle solver).

The swap corpus board lives under wk/ (generated by the #411 tooling); tests
skip when it is absent. The control-board no-op test is the R2 false-positive
guard: reconstructing a CORRECT board must not move anything.
"""
import os
import subprocess
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SWAP = os.path.join(ROOT, 'wk', 'b2', 'tigard__swap', 'd0',
                    'perturbed.kicad_pcb')
CONTROL = os.path.join(ROOT, 'wk', 'b2', 'tigard__swap', 'd0',
                       'perturbed.control.kicad_pcb')


def run_reconstruct(board, out, *extra):
    env = dict(os.environ, PYTHONPATH=ROOT)
    return subprocess.run(
        [sys.executable, '-X', 'utf8',
         os.path.join(ROOT, 'place_reconstruct.py'), board, out,
         '--clearance', '0.09', *extra],
        capture_output=True, text=True, env=env, cwd=ROOT)


class TestReconstructSwap(unittest.TestCase):
    def test_swap_board_reaches_zero_pad_conflicts(self):
        if not os.path.exists(SWAP):
            self.skipTest('swap corpus board not present')
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            out = os.path.join(td, 'recon.kicad_pcb')
            r = run_reconstruct(SWAP, out)
            self.assertIn(r.returncode, (0,), r.stdout + r.stderr)
            sys.path.insert(0, ROOT)
            from kicad_parser import parse_kicad_pcb
            from placement.legality import grade_pad_legality
            g = grade_pad_legality(parse_kicad_pcb(out), 0.09)
            self.assertEqual(g['pad_conflicts'], 0, g['worst'])
            self.assertEqual(g['hole_conflicts'], 0)
            # S1 anti-evacuation: off-board pad copper must not EXCEED the
            # input board's own amount (the input carries the displaced H1
            # and the by-design SW1 overhang).
            g0 = grade_pad_legality(parse_kicad_pcb(SWAP), 0.09)
            self.assertLessEqual(g['oob_pad_amount'],
                                 g0['oob_pad_amount'] + 1e-6)

    def test_control_board_untouched(self):
        if not os.path.exists(CONTROL):
            self.skipTest('control board not present')
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            out = os.path.join(td, 'recon.kicad_pcb')
            r = run_reconstruct(CONTROL, out)
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
            sys.path.insert(0, ROOT)
            from kicad_parser import parse_kicad_pcb
            a = parse_kicad_pcb(CONTROL)
            b = parse_kicad_pcb(out)
            moved = [ref for ref, fp in a.footprints.items()
                     if abs(b.footprints[ref].x - fp.x)
                     + abs(b.footprints[ref].y - fp.y) > 1e-6]
            self.assertEqual(moved, [])


if __name__ == '__main__':
    unittest.main()
